title: David Ruthven
logo: docs/assets/headshot_circle.png
description: Database Advisor
#show_downloads: true
#theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
#remote_theme: mmistakes/minimal-mistakes
